# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GTFS_miner
                                 A QGIS plugin
 Extraction facile des données GTFS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-11-08
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Wei SI Transamo
        email                : wei.si@transamo.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction,QFileDialog,QProgressBar

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
# Import the code for the dialog
from .GTFS_miner_dialog import GTFS_minerDialog
import os
import time
from datetime import datetime
from pathlib import Path

# 新模块化导入
from .gtfs_utils import str_time_hms
from .gtfs_norm import read_input, ligne_generate
from .gtfs_spatial import ag_ap_generate_reshape
from .gtfs_generator import (
    itineraire_generate, itiarc_generate, course_generate, 
    sl_generate, service_date_generate, service_jour_type_generate,
    nb_passage_ag, nb_course_ligne, caract_par_sl, 
    kcc_course_ligne, kcc_course_sl, corr_sl_shape, passage_arc
)
from .gtfs_export import (
    MEF_serdate, MEF_servjour, MEF_course, MEF_iti, 
    MEF_iti_arc, MEF_ligne, trace_sl_vol_oiseau
)
from .gtfs_qgis_adapter import (
    create_qgsLines, Qgs_PassageAG, shapefileWriter, 
    aggregate_polylines_by_category
)

from qgis.core import QgsProject


class GTFS_miner:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GTFS_miner_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&GTFS Miner')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GTFS_miner', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/GTFS_miner/Resources/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'GTFS Miner'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&GTFS Miner'),
                action)
            self.iface.removeToolBarIcon(action)

    def select_input_dir(self):
        input_dirname = QFileDialog.getExistingDirectory(self.dlg, "Sélectionnez le dossier des fichiers sources")
        if len(input_dirname) >0 :
            self.dlg.lineEdit_input.setText(input_dirname)

    def select_output_dir(self):
        output_dirname = QFileDialog.getExistingDirectory(self.dlg, "Sélectionnez le dossier des fichiers traités")
        if len(output_dirname) >0 :
            self.dlg.lineEdit_output.setText(output_dirname)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = GTFS_minerDialog()
        self.dlg.comboBox_zonevac.addItems(['Type_Jour_Vacances_A','Type_Jour_Vacances_B','Type_Jour_Vacances_C'])
        self.dlg.progressBar.setMinimum(1)
        self.dlg.progressBar.setMaximum(100)
        self.dlg.progressBar.setValue(1)
        self.dlg.helpText.setText("Test test test...\n\n")
        self.dlg.pushButton_input.clicked.connect(self.select_input_dir)
        self.dlg.pushButton_output.clicked.connect(self.select_output_dir)
        self.dlg.execute.clicked.connect(self.lancer)
        self.dlg.dev_test.clicked.connect(self.test)
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            self.dlg.lineEdit_input.clear()
            self.dlg.lineEdit_output.clear()
            self.dlg.progressText.clear()
            self.dlg.comboBox_zonevac.clear()
            self.dlg.pushButton_input.clicked.disconnect()
            self.dlg.pushButton_output.clicked.disconnect()
            self.dlg.execute.clicked.disconnect()
            self.dlg.dev_test.clicked.disconnect()

    def lancer(self):
        # Affichage en fonction de la sélection utilisateur
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Traitement des données GTFS vient de commencer!")
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Le processus peut durer environ 5 - 10 minutes. Si QGIS ne répond plus, c'est normal. Prenez un café en attendant.")
        t0 = round(time.time(),2)

        # Read raw data
        # User Input
        rawPath = self.dlg.lineEdit_input.text() # Input path of user selection
        output_path = self.dlg.lineEdit_output.text() # Output path of user selection
        time1 =self.dlg.timeEditDebutHPM.time() # User input time bin for periods
        time2 =self.dlg.timeEditFinHPM.time()
        time3 =self.dlg.timeEditDebutHPS.time()
        time4 =self.dlg.timeEditFinHPS.time()
        type_vac = self.dlg.comboBox_zonevac.currentText()
        debut_hpm = time1.hour()/24 + time1.minute()/1440
        fin_hpm = time2.hour()/24 + time2.minute()/1440
        debut_hps = time3.hour()/24 + time3.minute()/1440
        fin_hps = time4.hour()/24 + time4.minute()/1440
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: {output_path}")
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Lire les données brutes GTFS depuis le dossier choisi...")

        # Créer table données brutes
        GTFS_norm, Dates, validite = read_input(rawPath,self.plugin_dir )
        self.dlg.progressBar.setValue(5)
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Lecture des données brutes terminée.")
        stops = GTFS_norm['stops']
        routes = GTFS_norm['routes']
        stop_times = GTFS_norm['stop_times']
        initial_na = GTFS_norm['initial_na']
        final_na_time_col = GTFS_norm['final_na_time_col']
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Voici les colonnes ayant valeur NA dans la table Stop_times: {initial_na}")
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Nombre de NA dans les colonnes 'arrival_time' and 'departure_time' après traitement: {final_na_time_col}.")

        trips = GTFS_norm['trips']
        calendar = GTFS_norm['calendar']
        calendar_dates = GTFS_norm['calendar_dates']
        route_id_coor= GTFS_norm['route_id_coor']
        trip_id_coor = GTFS_norm['trip_id_coor']
        ser_id_coor = GTFS_norm['ser_id_coor']

        all_tables = " ; ".join(str(key) for key in GTFS_norm.keys())
        shapes_exist = "shapes" in GTFS_norm.keys()
        if shapes_exist:
            shapes =  GTFS_norm['shapes']
            shapes['shape_id'] = shapes['shape_id'].astype(str)
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Les fichiers présents dans le jeu de données GTFS sont les suivants: {all_tables}.")        
        del GTFS_norm

        # Créer tables arrêts génériques et physiques
        ## format standard
        AP, AG, marker = ag_ap_generate_reshape(stops)
        ## Ecriture en csv
        AG.to_csv(f'{output_path}/A_1_Arrets_Generiques.csv', sep=';', index = False)
        AP.to_csv(f'{output_path}/A_2_Arrets_Physiques.csv', sep=';', index = False)
        ## Affichage
        self.dlg.progressBar.setValue(10)
        nb_AP = str(len(AP))
        nb_AG = str(len(AG))
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Création des arrêts génériques et physiques terminée.")
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Les arrêts génériques sont générés avec {marker}.")
        self.dlg.progressText.append(f"Nombre d'arrêts génériques: {nb_AG}")
        self.dlg.progressText.append(f"Nombre d'arrêts physiques: {nb_AP}")

        # Create table ligne
        lignes = ligne_generate(routes)

        # Create itineraire
        itineraire = itineraire_generate(stop_times, AP, trips)
        del stop_times
        
        ## Affichage
        self.dlg.progressBar.setValue(20)
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Création de la table itinéraires terminée.")

        # Create itineraire arc
        itineraire_arc = itiarc_generate(itineraire,AG)
        ## Affichage
        self.dlg.progressBar.setValue(25)
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Création de la table itinéraires arcs terminées.")

        # Create courses
        courses = course_generate(itineraire,itineraire_arc)
        self.dlg.progressBar.setValue(30)
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Création de la table courses terminées.")

        # Create Sous lignes
        sous_ligne = sl_generate(courses, AG,lignes)
        sous_ligne.to_csv(f'{output_path}/B_2_Sous_Lignes.csv', sep=';', index = False)

        self.dlg.progressBar.setValue(40)
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Création de la table sous lignes terminées.")
        nb_sl = str(len(sous_ligne))
        self.dlg.progressText.append("Nombre de sous lignes : " +  nb_sl)

        # Create service date et services jour type
        service_dates, msg = service_date_generate(calendar ,calendar_dates,Dates)
        service_dates_export = MEF_serdate(service_dates,ser_id_coor)
        service_dates_export.to_csv(f'{output_path}/D_1_Service_Dates.csv', sep=';', index = False)
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: {msg}")
        self.dlg.progressBar.setValue(45)

        service_jour_type = service_jour_type_generate(service_dates, courses, type_vac)
        service_jour_type_export = MEF_servjour(service_jour_type, route_id_coor, ser_id_coor, type_vac)
        service_jour_type_export.to_csv(f'{output_path}/D_2_Service_Jourtype.csv', sep=';', index = False)

        # mise en forme COURSES/ITINERAIRE/ITI_ARC en fonction du choix utilisateur
        courses_export = MEF_course(courses, trip_id_coor)
        courses_export.to_csv(f'{output_path}/C_1_Courses.csv', sep=';', index = False)

        itineraire_export = MEF_iti(itineraire,courses)
        itineraire_export.to_csv(f'{output_path}/C_2_Itineraire.csv', sep=';', index = False)

        iti_arc_export = MEF_iti_arc(itineraire_arc,courses)
        iti_arc_export.to_csv(f'{output_path}/C_3_Itineraire_Arc.csv', sep=';', index = False)

        # Ajouter information OD principal
        lignes_export = MEF_ligne(lignes,courses_export,AG)
        ## Ecriture en csv
        lignes_export.to_csv(f'{output_path}/B_1_Lignes.csv', sep=';', index = False)
        del routes
        ## Affichage
        self.dlg.progressBar.setValue(55)
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Création de la table lignes terminée.")
        nb_lignes = str(len(lignes))
        self.dlg.progressText.append(f"Nombre de lignes: {nb_lignes}")
        
        ## Affichage
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Mise en forme des tables terminées!")
        self.dlg.progressBar.setValue(60)

        # Créer les tracé des lignes QGIS
        layer_name = 'G_1_Trace_Sous_Ligne'
        if shapes_exist:
            shape_sl = corr_sl_shape(courses, trips, shapes, sous_ligne)
            traces_layer = create_qgsLines(shape_sl, layer_name, 'shape_pt_lon', 'shape_pt_lat')

            # transform sl length layer to data.frame
            attribs = [f.name() for f in traces_layer.fields()]
            data = []           
            for feat in traces_layer.getFeatures():
                data.append(feat.attributes())
            sl_long = pd.DataFrame(data,columns = attribs)
            self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Tracé du fichier Shapes utilisé.")
            sl_long.drop(['id_ligne_num','route_short_name', 'route_long_name'],axis = 1, inplace = True)
            sous_ligne = sous_ligne.merge(sl_long, on = 'sous_ligne')
            sous_ligne.rename({'length':'Dist_shape'}, axis = 1, inplace = True)
            sous_ligne.to_csv(f'{output_path}/B_2_Sous_Lignes.csv', sep=';', index = False)
            sl_dist = sous_ligne[['sous_ligne','Dist_shape']]
            courses_export = courses_export.merge(sl_dist, on = 'sous_ligne')
            courses_export.to_csv(f'{output_path}/C_1_Courses.csv', sep=';', index = False)

        else:
            table_iti_sl = trace_sl_vol_oiseau(itineraire_export, AG, sous_ligne)
            traces_layer = create_qgsLines(table_iti_sl, layer_name, 'stop_lon', 'stop_lat')
            self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Tracé au vol d'oiseau entre arrêts.")
        traces_layer.setName(layer_name)
        QgsProject.instance().addMapLayer(traces_layer)
        shapefileWriter(traces_layer, output_path, layer_name)
        del trips
        layer_name = 'G_2_Trace_Ligne'
        ligne_traces_layer = aggregate_polylines_by_category(traces_layer, layer_name)
        QgsProject.instance().addMapLayer(ligne_traces_layer)
        shapefileWriter(ligne_traces_layer, output_path, layer_name)


        ## Affichage
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Création des tracés de sous-ligne terminées!")
        self.dlg.progressBar.setValue(65)

        # tables supplémentaires
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Création des tables supplémentaires...")
        ## Création de la table nombre de passages par AG
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Création de la table nombre de passages par AG.")
        nb_passage_ag_typejour = nb_passage_ag(service_jour_type_export, itineraire_export, AG, type_vac)
        nb_passage_ag_typejour.to_csv(f'{output_path}/E_1_Nombre_Passage_AG.csv', sep=';', index = False)

        ## Création de la table nombre de courses par ligne
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Création de la table nombre de courses par ligne.")
        nb_course_ligne_typejour = nb_course_ligne(service_jour_type_export, courses_export, type_vac,lignes_export)
        nb_course_ligne_typejour.to_csv(f'{output_path}/F_1_Nombre_Courses_Lignes.csv', sep=';', index = False)

        ## Création de la table fréquence des sous-ligne par période de la journée
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Création de la table fréquence des sous-ligne par période de la journée.")
        caract_sl = caract_par_sl(service_jour_type_export,courses_export,debut_hpm , fin_hpm, debut_hps ,fin_hps, type_vac,sous_ligne)
        caract_sl.to_csv(f'{output_path}/F_2_Caract_SousLignes.csv', sep=';', index = False)
        self.dlg.progressBar.setValue(70)

        ## KCC
        kcc_ligne = kcc_course_ligne(service_jour_type_export, courses_export,type_vac, lignes_export, shapes_exist)
        kcc_ligne.to_csv(f'{output_path}/F_3_KCC_Lignes.csv', sep=';', index = False)
        kcc_sl = kcc_course_sl(service_jour_type_export, courses_export,type_vac, sous_ligne, shapes_exist)
        kcc_sl.to_csv(f'{output_path}/F_4_KCC_Sous_Ligne.csv', sep=';', index = False)

        # Passage par AG sur QGIS
        psg_ag = Qgs_PassageAG(nb_passage_ag_typejour,output_path)
        QgsProject.instance().addMapLayer(psg_ag)
        # Rename the output layer with a custom name
        custom_name = 'E_1_Nombre_Passage_AG'
        psg_ag.setName(custom_name)

        shapefileWriter(psg_ag, output_path, custom_name)

        # Psudo-réseau GTFS
        pnode = AG[['id_ag_num','stop_name','stop_lon','stop_lat']].rename({'id_ag_num':'NO','stop_name':'NAME','stop_lon':'LON','stop_lat':'LAT'},axis = 1)
        plink = iti_arc_export.groupby(['id_ag_num_a','id_ag_num_b','DIST_Vol_Oiseau'],as_index = False)['id_course_num'].count().reset_index(drop = True)
        plink['ID'] = plink.index
        plink = plink[['ID','id_ag_num_a','id_ag_num_b','DIST_Vol_Oiseau']].rename({'ID':'ID_ARC','id_ag_num_a':'FROMNODE','id_ag_num_b':'TONODE','DIST_Vol_Oiseau':'LENGTH'},axis = 1)

        nb_passage_arc = passage_arc(iti_arc_export, service_jour_type, pnode,type_vac)
        nb_passage_arc.to_csv(f'{output_path}/E_4_Nombre_Passage_Arc.csv', sep=';', index = False)

        # Passage par arc sur QGIS
        psg_arc = Qgs_PassageArc(nb_passage_arc, output_path)
        custom_name = 'E_4_Nombre_Passage_Arc'
        psg_arc.setName(custom_name)
        QgsProject.instance().addMapLayer(psg_arc)
        # Write to an ESRI Shapefile format dataset using UTF-8 text encoding
        shapefileWriter(psg_arc, output_path, custom_name)
        ## Affichage
        self.dlg.progressText.append(f"{datetime.now():%H:%M:%S}: Création des .shp pour passage AG/ARC terminées!")
        self.dlg.progressBar.setValue(75)

        t9 = time.time()
        success_message = f'Extraction terminée! Le petit a pris {round(t9 - t0)} seconds pour faire tout ce boulot. Donne lui un bravo :)'
        self.dlg.progressText.append(success_message)
        self.dlg.progressBar.setValue(100)

    def test(self):
        pass




