"""Spec §5.1 A. Productivity indicators (8 items).

Phase 2 Task 2.1 implements 3 of 8:
    prod_kcc_year, prod_lines_count, prod_stops_count.

Tasks 2.2 / 2.3 will fill the remaining 5 (prod_courses_day_avg,
prod_peak_hour_courses, prod_service_amplitude, prod_network_length_km,
prod_peak_vehicles_needed).
"""
from __future__ import annotations

from typing import Mapping

import pandas as pd


def compute_all(
    raw: Mapping[str, pd.DataFrame],
    normed: dict,
    meta,                                  # AomMeta — no annotation to dodge circular import
) -> dict[str, float | None]:
    """Compute the productivity indicators implemented in Task 2.1.

    Input Schema:
        raw: dict-of-DataFrames from `read_gtfs_zip` — needs at minimum
             "routes" with `route_id`.
        normed: NormedGTFS dict from `gtfs_normalize` — needs "stops",
                "stop_times", "trips", "calendar", "calendar_dates",
                "trip_id_coor", plus the normalized "routes".
        meta: AomMeta — unused by Task 2.1 but kept for signature symmetry
              with `density.compute_all` (which takes `meta` for
              area_km2 / population denominators).

    Output Schema:
        {
            "prod_kcc_year":     float (km, sum of F_3_KCC_Lignes grid),
            "prod_lines_count":  float (count of unique route_id in raw),
            "prod_stops_count":  float (count of physical stops, location_type=0),
        }
        Missing/unavailable values resolve to None.
    """
    out: dict[str, float | None] = {}

    out["prod_kcc_year"] = _kcc_year(raw, normed)
    out["prod_lines_count"] = float(raw["routes"]["route_id"].nunique())

    stops = normed["stops"]
    if "location_type" in stops.columns:
        physical = stops[stops["location_type"].fillna(0).astype(int) == 0]
    else:
        physical = stops
    out["prod_stops_count"] = float(physical["stop_id"].nunique())

    return out


def _kcc_year(raw: Mapping[str, pd.DataFrame], normed: dict, type_vac: str = "Type_Jour") -> float:
    """Spec §11 contract anchor: must match worker pipeline F_3_KCC_Lignes within 0.1%.

    Reproduces the chain that produces F_3_KCC_Lignes (worker.py:255-325 and
    gtfs_core.pipeline.run_pipeline). Returns the sum of all KCC cells across
    the pivot — equivalent to baselines.json.kcc_grand_total.

    Re-includes spatial clustering (`ag_ap_generate_reshape`) which spec §6.2
    marks "[skip]" for the panel pipeline, but the equivalence contract requires
    bit-equivalent output of `kcc_course_ligne`, which transitively requires
    the spatial step. A faster KCC that bypasses the cluster is V1+ work.

    Note on `type_vac`: the d4 baselines were generated by `pipeline.run_pipeline`
    with the default `PipelineConfig()` (type_vac='Type_Jour') and a
    `NullCalendarProvider` (no XLS holidays injected). This implementation
    matches that — no provider call here, just `Type_Jour`.
    """
    from app.services.gtfs_core.gtfs_norm import ligne_generate
    from app.services.gtfs_core.gtfs_spatial import ag_ap_generate_reshape
    from app.services.gtfs_core.gtfs_generator import (
        course_generate,
        itiarc_generate,
        itineraire_generate,
        kcc_course_ligne,
        service_date_generate,
        service_jour_type_generate,
    )
    from app.services.gtfs_core.gtfs_export import MEF_course, MEF_ligne
    from app.services.gtfs_core.pipeline import build_dates_table

    # 1. Spatial clustering — produces AP, AG (used downstream by itineraire / arc).
    AP, AG, _marker = ag_ap_generate_reshape(normed["stops"])

    # 2. Itinerary, arcs, courses (worker.py:262-274 / pipeline.py:127-136).
    #    `ligne_generate` operates on the normalized `routes` (worker passes
    #    `normed['routes']`, not raw), because it needs `route_type` already
    #    coerced to int8 and `id_ligne_num` already assigned.
    lignes = ligne_generate(normed["routes"])
    itineraire = itineraire_generate(normed["stop_times"], AP, normed["trips"])
    itineraire_arc = itiarc_generate(itineraire, AG)
    courses = course_generate(itineraire, itineraire_arc)

    # `kcc_course_ligne` reads `id_ligne_num`, `id_service_num`, `DIST_Vol_Oiseau`
    # from the courses arg — `MEF_course` is the function that surfaces
    # `id_service_num` into the export-shaped row, so we must run it here too.
    courses_export = MEF_course(courses, normed["trip_id_coor"])
    lignes_export = MEF_ligne(lignes, courses_export, AG)

    # 3. Service dates + jour-type. The 3rd `Dates` arg is mandatory in the
    # current signature; we build it via `build_dates_table` exactly as
    # `pipeline.run_pipeline` does (with a no-op enrich = NullCalendarProvider).
    Dates = build_dates_table(normed["calendar"], normed["calendar_dates"])
    service_dates, _msg = service_date_generate(
        normed["calendar"], normed["calendar_dates"], Dates
    )

    # Graceful fallback (worker.py:296-298, pipeline.py:152-154): if the
    # requested type_vac column was not produced (e.g. XLS provider missed
    # dates, or NullProvider was used), fall back to plain 'Type_Jour'.
    if type_vac not in service_dates.columns:
        type_vac = "Type_Jour"

    sjt = service_jour_type_generate(service_dates, courses, type_vac)

    # 4. F_3_KCC_Lignes: pivoted [id_ligne_num × type_vac value], cells in km.
    kcc_df = kcc_course_ligne(sjt, courses_export, type_vac, lignes_export, False)

    # 5. Grand total = sum across all numeric jour_type columns × all rows.
    id_cols = {"id_ligne_num", "route_short_name", "route_long_name"}
    jt_cols = [c for c in kcc_df.columns if c not in id_cols]
    return float(kcc_df[jt_cols].sum().sum())
