"""add_calendar_dates_table

Revision ID: 65dc0a60ef68
Revises: d9633f79a841
Create Date: 2026-04-11 18:15:01.842496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65dc0a60ef68'
down_revision: Union[str, None] = 'd9633f79a841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_dates',
    sa.Column('date_gtfs', sa.String(length=8), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=True),
    sa.Column('holiday_name', sa.String(), nullable=True),
    sa.Column('zone_a', sa.Boolean(), nullable=True),
    sa.Column('zone_b', sa.Boolean(), nullable=True),
    sa.Column('zone_c', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('date_gtfs')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_dates')
    # ### end Alembic commands ###
